export const produtos = [
  {
    id: 0,
    nome: "Smartphone Samsung Galaxy S23",
    categoria: "Celular",
    preco: 4999.9,
    estoque: 15,
  },
  {
    id: 1,
    nome: "Smartphone Samsung Galaxy S23",
    categoria: "Celular",
    preco: 4999.9,
    estoque: 15,
  },
  {
    id: 2,
    nome: "Notebook Dell Inspiron 15",
    categoria: "Notebook",
    preco: 3899.0,
    estoque: 8,
  },
  {
    id: 3,
    nome: "Smart TV LG 55pol. 4K",
    categoria: "Televisão",
    preco: 3499.9,
    estoque: 12,
  },
  {
    id: 4,
    nome: "Fone de Ouvido Bluetooth JBL",
    categoria: "Áudio",
    preco: 399.9,
    estoque: 25,
  },
  {
    id: 5,
    nome: "Console PlayStation 5",
    categoria: "Games",
    preco: 4299.99,
    estoque: 6,
  },
  {
    id: 6,
    nome: "Câmera Digital Canon EOS Rebel",
    categoria: "Fotografia",
    preco: 2799.0,
    estoque: 4,
  },
  {
    id: 7,
    nome: "Caixa de Som Alexa Echo Dot",
    categoria: "Assistente Virtual",
    preco: 349.0,
    estoque: 18,
  },
  {
    id: 8,
    nome: "Monitor Gamer Acer 27pol. 144Hz",
    categoria: "Periféricos",
    preco: 1699.9,
    estoque: 10,
  },
  {
    id: 9,
    nome: "Teclado Mecânico Redragon",
    categoria: "Periféricos",
    preco: 299.9,
    estoque: 20,
  },
  {
    id: 10,
    nome: "Drone DJI Mini 3 Pro",
    categoria: "Drones",
    preco: 5699.0,
    estoque: 3,
  },
  {
    id: 11,
    nome: "Tablet Apple iPad 10ª Geração",
    categoria: "Tablet",
    preco: 3499.0,
    estoque: 7,
  },
  {
    id: 12,
    nome: "Smartwatch Apple Watch Series 9",
    categoria: "Wearable",
    preco: 3999.9,
    estoque: 9,
  },
  {
    id: 13,
    nome: "Caixa de Som JBL Boombox 3",
    categoria: "Áudio",
    preco: 2899.0,
    estoque: 5,
  },
  {
    id: 14,
    nome: "Console Xbox Series X",
    categoria: "Games",
    preco: 4499.9,
    estoque: 8,
  },
  {
    id: 15,
    nome: "Notebook MacBook Air M2",
    categoria: "Notebook",
    preco: 8999.0,
    estoque: 4,
  },
  {
    id: 16,
    nome: "Câmera GoPro Hero 11 Black",
    categoria: "Fotografia",
    preco: 2499.0,
    estoque: 10,
  },
  {
    id: 17,
    nome: "Headset Gamer HyperX Cloud II",
    categoria: "Áudio",
    preco: 599.9,
    estoque: 16,
  },
  {
    id: 18,
    nome: "Monitor LG UltraWide 34pol.",
    categoria: "Periféricos",
    preco: 2999.9,
    estoque: 6,
  },
  {
    id: 19,
    nome: "Smart TV Samsung QLED 65pol.",
    categoria: "Televisão",
    preco: 7999.9,
    estoque: 5,
  },
  {
    id: 20,
    nome: "Kindle Paperwhite 11ª Geração",
    categoria: "Leitor Digital",
    preco: 699.0,
    estoque: 12,
  },
  {
    id: 21,
    nome: "Smartphone iPhone 15 Pro Max",
    categoria: "Celular",
    preco: 10999.9,
    estoque: 8,
  },
  {
    id: 22,
    nome: "Tablet Samsung Galaxy Tab S9",
    categoria: "Tablet",
    preco: 4699.9,
    estoque: 5,
  },
  {
    id: 23,
    nome: "Console Nintendo Switch OLED",
    categoria: "Games",
    preco: 2499.9,
    estoque: 9,
  },
  {
    id: 24,
    nome: "Projetor Epson PowerLite",
    categoria: "Projetores",
    preco: 3299.9,
    estoque: 4,
  },
  {
    id: 25,
    nome: "Caixa de Som iPhone SRS-XB43",
    categoria: "Áudio",
    preco: 1299.9,
    estoque: 11,
  },
  {
    id: 26,
    nome: "Teclado Logitech MX Keys",
    categoria: "Periféricos",
    preco: 799.9,
    estoque: 15,
  },
  {
    id: 27,
    nome: "Câmera Sony Alpha a6400",
    categoria: "Fotografia",
    preco: 6399.0,
    estoque: 3,
  },
  {
    id: 28,
    nome: "Monitor Samsung Odyssey G9",
    categoria: "Periféricos",
    preco: 8499.9,
    estoque: 2,
  },
  {
    id: 29,
    nome: "Smart TV TCL 50pol. 4K",
    categoria: "Televisão",
    preco: 2499.9,
    estoque: 14,
  },
  {
    id: 30,
    nome: "Smartwatch Samsung Galaxy Watch 6",
    categoria: "Wearable",
    preco: 1999.9,
    estoque: 10,
  },
];